FROM node:12

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Installing dependencies
COPY package*.json /usr/src/app/
RUN npm ci --production && npm clean cache --force
RUN npm run build

# Copying source files
COPY . /usr/src/app

# Running the app
CMD ["npm", "run", "start"]