FROM node:12



# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Installing dependencies
COPY package*.json /usr/src/app/
RUN npm ci --production

COPY . /usr/src/app

RUN npm run build

CMD ["npm", "run", "start"]