version: '2.0'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
      - /usr/src/app/.next
