version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
workflows:
  build:
    jobs:
      - cypress/install:
        build: npm run build
      - cypress/run:
          requires:
            - cypress/install
          start: npm run start
          wait-on: 'http://localhost:3000'
          no-workspace: true
          post-steps:
            - store_artifacts:
                path: coverage
            - run: npm run check:cov
